###
#  This file was generated by bootstrap do not edit manually
###

domains_to_allow                            = ${domains_to_allow}
billing_data_users                          = "${billing_data_users}"
audit_data_users                            = "${audit_data_users}"
org_id                                      = "${org_id}"
billing_account                             = "${billing_account}"
terraform_service_account                   = "${terraform_service_account}"
default_region                              = "${default_region}"
scc_notification_name                       = "${scc_notification_name}"
parent_folder                               = "${parent_folder}"
scc_notification_filter                     = "${scc_notification_filter}"
create_access_context_manager_access_policy = "${create_access_context_manager_access_policy}"
enable_hub_and_spoke                        = "${enable_hub_and_spoke}"

